[phases.setup]
nixPkgs = ['python311', 'postgresql', 'gcc']

[phases.install]
cmds = ['curl -L --output uv https://github.com/astral-sh/uv/releases/download/0.1.24/uv-linux-aarch64',
        'chmod +x uv',
        './uv pip install -r requirements.txt']

[phases.build]
cmds = ['./uv run python manage.py collectstatic --noinput']

[start]
cmd = "./uv run python -m gunicorn ecfr.wsgi:application --bind=0.0.0.0:$PORT" 