# Generated by Django 5.1.6 on 2025-02-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfrreference',
            name='subpart',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
