# Generated by Django 5.1.6 on 2025-02-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulations', '0002_cfrreference_subpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfrreference',
            name='full_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cfrreference',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
